<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Condition="'$(Configuration)'=='Debug'" Command="dotnet run --project &quot;$(ProjectDir)../DemoContentBuilder&quot; -- &quot;$(ProjectDir)DemoRenderer.content&quot; -debug" />
    <Exec Condition="'$(Configuration)'!='Debug'" Command="dotnet run --project &quot;$(ProjectDir)../DemoContentBuilder&quot; -- &quot;$(ProjectDir)DemoRenderer.content&quot;" />
  </Target>

  <ItemGroup>
    <ProjectReference Include="../../BepuPhysics/BepuPhysics.csproj" />
    <ProjectReference Include="../DemoContentLoader/DemoContentLoader.csproj" />
    <ProjectReference Include="../DemoUtilities/DemoUtilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DemoRenderer.contentarchive" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
  </ItemGroup>
</Project>
