<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Contents\Carlito-Regular.font" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Parcel.NExT\Packages\Divooka.Physics.RBD\Divooka.Physics.RBD.csproj" />
    <ProjectReference Include="..\..\..\..\Parcel.NExT\Packages\Divooka.Physics.Rendering\Divooka.Physics.Rendering.csproj" />
    <ProjectReference Include="..\BEPU.Demos.Framework\BEPU.Demos.Framework.csproj" />
    <ProjectReference Include="..\DemoRenderer.GL\DemoRenderer.GL.csproj" />
  </ItemGroup>

</Project>
