<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>2.5.0-beta.24</Version>
    <Description>Supporting utilities library for BEPUphysics v2.</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <Optimize>false</Optimize>
    <DefineConstants>TRACE;DEBUG;CHECKMATH</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <Optimize>true</Optimize>
    <DefineConstants>TRACE;RELEASE</DefineConstants>
  </PropertyGroup>

</Project>